### PR TITLE
Update import_mordor.rst minor typo

### PR DESCRIPTION
**Pull request by jwsy**

### CODE REVIEW

**Comment by jwsy** [comment]
Going to take the opportunity here to thank @Cyb3rWard0g & team for such fantastic work and documentation!

**Comment by Cyb3rWard0g** [comment]
Thank you very much for the feedback @jwsy !! :) I have a few things being released this week ! I hope you can test them and let me know what you think. Thank you for the PR

**Comment by jwsy** [comment]
FYI - video of me setting up HELK on Google Cloud 20 min video - fastest/cheapest (max $2 a day after your first year) way to ELK with data. Note that I’ll want to open port 9200 and some others later but the hardest part is registering for a GCP account https://drive.google.com/file/d/1vwfjuD19UNLtqsSsv4sqMhD5VP1Z-DIX/view?usp=drivesdk

**Comment by jessefmoore** [comment]
Hi Jason, will you changing permissions on that Google drive to allow everyone to access it?

Thank you,
-Jesse

**Comment by jwsy** [comment]
I’ve updated the permissions. Sorry about that!

**Pull request merged**
